// <auto-generated />
namespace S2022A6LLC.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class a6lenghtyalbumartistpropsmigration : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(a6lenghtyalbumartistpropsmigration));
        
        string IMigrationMetadata.Id
        {
            get { return "202208051521206_a6-lenghty-album-artist-props-migration"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
