// <auto-generated />
namespace S2022A6LLC.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class a6trackaudioaudiotype : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(a6trackaudioaudiotype));
        
        string IMigrationMetadata.Id
        {
            get { return "202208052119506_a6-track-audio-audiotype"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
